#!/bin/bash

#PBS -l nodes=1:ppn=1,walltime=00:10:00
#PBS -l vmem=4gb
#PBS -N kwyk_neuronet
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:p100:2

#parse config.json for input parameters
#singularity run -B $(pwd):/data -W /data --nv kwyk_latest-gpu.sif -m bvwn_multi_prior -n 2 --save-variance --save-entropy T1_001.nii.gz output.nii.gz

export SINGULARITYENV_OMP_NUM_THREADS=1
model=$(jq -r .model config.json)
samples=$(jq -r .samples config.json)


sv=$(jq -r .save_variance config.json)
se=$(jq -r .save_entropy config.json)

if $sv; then
	save_var="--save-variance"
else
	save_var=""
fi

if $se; then
	save_ent="--save-entropy"
else
	save_ent=""
fi


t1=$(jq -r .t1 config.json)
out=$(jq -r .out config.json)

# singularity pull --docker-login docker://neuronets/kwyk:latest-gpu
# singularity run -B $(pwd):./ -W ./ --nv kwyk_latest-gpu.sif -m $model -n $samples $save_var $save_ent $sv $se $t1 $out

singularity exec --nv -e docker://neuronets/kwyk:latest-gpu nobrainer_bwn -m $model -n $samples $save_var $save_ent $t1 $out
