#!/bin/bash

#PBS -l nodes=1:ppn=1,walltime=00:10:00
#PBS -l vmem=4gb
#PBS -N kwyk_neuronet
#SBATCH --gres=gpu:p100:2

set -e
set -x

model=$(jq -r .model config.json)
if [ $model != "bwn" ]; then
	save_var="--save-variance"
fi

export SINGULARITYENV_OMP_NUM_THREADS=1
singularity exec --nv -e docker://neuronets/kwyk:latest-gpu nobrainer_bwn \
	-m $model \
	-n $(jq -r .samples config.json) \
	$save_var \
	--save-entropy \
	$(jq -r .t1 config.json) output.nii.gz

#format output to 2 brainlife datatypes
mkdir -p output_fs
mv output_means.nii.gz output_fs/means.nii.gz
mv output_entropy.nii.gz output_fs/entropy.nii.gz

mkdir -p output 
mv output_means_orig.nii.gz output/means.nii.gz
mv output_entropy_orig.nii.gz output/entropy.nii.gz

if [ $model != "bwn" ]; then
	mv output_variance.nii.gz output_fs/variance.nii.gz
	mv output_variance_orig.nii.gz output/variance.nii.gz
fi
